### ISSUE TITLE
archiveコマンド

### ISSUE THREAD

**Issue by daima3629** [sizumita/dqs#14]
`.archive` (`.as ID archive`) で質問にarchive属性を付けられるようにしてほしい。
archiveされた質問は検索にヒットしなくなる。

---

**詳細な動作案**
- 表示
#質問の投稿と一覧 のembedでは、色を黒にする。
また、質問タイトルの前に`[Archived]` などの接頭詞をつける。

- 開かれている質問に対して行った場合
通常のcloseに加え、delayが終了したあとarchive属性をつける。
- asコマンドを使って行われた場合
そのままarchive属性をつける。

**Comment by sizumita** [comment]
trashコマンドが存在しています。
trashコマンドを使用すると質問一覧から削除され、検索にもヒットしなくなります。
asコマンドでも`as ID trash`が使用できます。
